
server:
  port: 9999
magic-api:
  #配置web页面入口
  web: /magic/web
  resource:
    #配置文件存储位置。当以classpath开头时，为只读模式
    #mac用户请改为可读写的目录
    #如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    location: D:/data/magic-api


spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:33062/magic-api-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: usbw

    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/mcsrb.db
    username:
    password:

hibernate:
  dialect: org.hibernate.community.dialect.SQLiteDialect

#debug: true
logging:
  level:
    root: debug

#  pattern:
#    console: "%d %clr(%p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
#    %boldGreen(%date{yyyy-MM-dd HH:mm:ss}) | %highlight(%-5level) | %cyan(%thread) | %magenta(%logger) | %n %msg %n%n
